- id: '1640849979199'
  alias: BBQ open
  description: ''
  trigger: []
  condition: []
  action:
  - service: cover.set_cover_position
    data:
      position: 0
    target:
      entity_id:
      - cover.pergola_tenda_nord
      - cover.tenda_gartenhusl
  mode: single
- id: '1650735139689'
  alias: Alarm when GARAGE-door left open
  description: ''
  triggers:
  - entity_id:
    - cover.garage_door
    to: closing
    for:
      hours: 0
      minutes: 0
      seconds: 10
    trigger: state
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.rudy_federici
      state:
      - not_home
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - condition: and
      conditions:
      - condition: state
        entity_id: device_tracker.mary_s_iphonex
        state: not_home
        for:
          hours: 0
          minutes: 5
          seconds: 0
  actions:
  - data:
      title: ALARM garage open
      message: Mary & Rudy left home but garage is NOT closed
    action: notify.notify
  mode: single
- id: '1653639138002'
  alias: Cambiatoio Toggle
  description: ''
  trigger: []
  condition: []
  action:
  - if:
    - condition: device
      device_id: a8bfbb58c69480ba17f25a3fdc6f168b
      domain: cover
      entity_id: cover.pergola_tenda_sud
      type: is_position
      above: 95
    then:
    - service: cover.set_cover_position
      data:
        position: 0
      target:
        entity_id: cover.pergola_tenda_sud
    - service: cover.set_cover_position
      data:
        position: 0
      target:
        entity_id:
        - cover.pergola_tenda_nord
        - cover.pergola_tenda_west
    else:
    - service: cover.set_cover_position
      data:
        position: 100
      target:
        entity_id: cover.pergola_tenda_sud
    - service: cover.set_cover_position
      data:
        position: 75
      target:
        entity_id:
        - cover.pergola_tenda_nord
        - cover.pergola_tenda_west
  mode: queued
- id: '1670965598190'
  alias: garage open at 22:00
  description: post alarm
  triggers:
  - at: '22:00:00'
    trigger: time
  - at: '23:00:00'
    trigger: time
  - at: '23:59:59'
    trigger: time
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.sonoff_100149f0c6
      state: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 0
  actions:
  - data:
      title: ALARM garage open
      message: it's night and the garage dppr is still open
    action: notify.notify
  mode: single
